helpdesk/dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'
urlpatterns = [
    path('', views.show_dashboard, name='dashboard'),
]

helpdesk/helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include

from ticket.views import QueryInfoAPI, ReplayInfoAPI

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('ticket/', include('ticket.urls')),
    path('', include('dashboard.urls')),
    path('api/', include('rest_framework.urls')),
    path('api/v1/query', QueryInfoAPI.as_view(), name='query-api'),
    path('api/v1/replay', ReplayInfoAPI.as_view(), name='replay-api'),
]

helpdesk/ticket/urls.py
from django.urls import path

from . import views

app_name = 'ticket'
urlpatterns = [
    path('create/', views.CreateQuery.as_view(), name='create-ticket'),
    path('view/', views.show_active_query, name='view-ticket'),
    path('detail/<str:pk>', views.DetailQueryReplay.as_view(), name='detail-query'),
    path('edit/<str:pk>', views.EditQueryCategoryView.as_view(), name='edit-query'),
    path('history/replay', views.HistoryListViewReplay.as_view(), name='list-history-replay'),
    path('history/operator', views.HistoryListViewOperator.as_view(), name='list-history-operator'),
    path('history/query', views.HistoryListViewQuery.as_view(), name='list-history-query'),
    path('close/<int:id>', views.set_cancel_status_query, name='close-query'),
]

helpdesk/user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='create-user'),
    path('login/', views.LoginView.as_view(), name='login-user'),
    path('logout/', views.LogoutView.as_view(), name='logout-user'),
    path('edit/', views.EditProfile.as_view(), name='edit-profile'),
]

helpdesk/dashboard/models.py
from django.db import models

# Create your models here.

helpdesk/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView

from ticket import models


@login_required
def show_dashboard(request):
    return render(request, template_name='dashboard/dashboard.html')

helpdesk/dashboard/templates/dashboard/base.html
{% load widget_tweaks %}
{% load static %}
<html>
<head>
    {% block head %}{% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="{% static 'base/css/font-awesome.min.css' %}"/>
    <link rel='stylesheet' href="{% static 'base/css/bootstrap.min.css' %}"/>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel='stylesheet' href="{% static 'base/css/style.css' %}"/>
    <script src="{% static 'base/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.bundle.min.js' %}"></script>
    <title>{% block page_header_title %} Dashboard {% endblock %}</title>
</head>
<body>
{% block navbar_menu %}
    <!-- Bootstrap NavBar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">
            {% if  user.is_authenticated %}
{#                <img src="https://media-exp1.licdn.com/dms/image/C4D03AQG8M7iJeCITgw/profile-displayphoto-shrink_200_200/0/1614260643050?e=1628726400&v=beta&t=GphmyJJNYwbiQ17z4vyRGQj-dwqRljAoD5JrqWSVK8g"#}
{#                     width="30" height="30"#}
                     <h4 class="fa fa-user fa-fw "></h4>
            {% endif %}
            {% if user.is_authenticated %}
                <span class="menu-collapsed"> {{ request.user.get_full_name }}</span>
            {% endif %}
        </a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                {% if not user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'user:login-user' %}">Login <span
                                class="sr-only">(current)</span></a>
                    </li>
                {% endif %}
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'query-api' %}">Rest-API</a>
                    </li>
                {% endif %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:dashboard' %}">Home</a>
                </li>
                <!-- This menu is hidden in bigger devices with d-sm-none.
               The sidebar isn't proper for smaller screens imo, so this dropdown menu can keep all the useful sidebar itens exclusively for smaller screens  -->
                <li class="nav-item dropdown d-sm-block d-md-none">
                    <a class="nav-link dropdown-toggle" href="#" id="smallerscreenmenu" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false"> Menu </a>
                    <div class="dropdown-menu" aria-labelledby="smallerscreenmenu">
                        <a class="dropdown-item" href="#top">Dashboard</a>
                        <a class="dropdown-item" href="#top">Profile</a>
                        <a class="dropdown-item" href="#top">Tasks</a>
                        <a class="dropdown-item" href="#top">Etc ...</a>
                    </div>
                </li><!-- Smaller devices menu END -->
            </ul>
        </div>
    </nav><!-- NavBar END -->
    <!-- Bootstrap row -->
    <div class="row" id="body-row">
    <!-- Sidebar -->
    <div id="sidebar-container" class="sidebar-expanded d-none d-md-block">
        <!-- d-* hidden the Sidebar in smaller devices. Its items can be kept on the Navbar 'Menu' -->
        <!-- Bootstrap List Group -->
        <ul class="list-group">
            <!-- Separator with title -->
            <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed">
                <small>MAIN MENU</small>
            </li>
            <!-- /END Separator -->
            <!-- Menu with submenu -->
            <a href="#submenu1" data-toggle="collapse" aria-expanded="false"
               class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-dashboard fa-fw mr-3"></span>
                    <span class="menu-collapsed">Dashboard</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>
            <!-- Submenu content -->
            <div id='submenu1' class="collapse sidebar-submenu">
                <a href="{% url 'ticket:view-ticket' %}"
                   class="list-group-item  list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed ">List</span>
                </a>
                <a href="{% url 'ticket:create-ticket' %}"
                   class="list-group-item  mr-3 list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Create</span>
                </a>
            </div>
            <a href="#submenu2" data-toggle="collapse" aria-expanded="false"
               class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-edit fa-fw mr-3"></span>
                    <span class="menu-collapsed ">Profile</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>
            <!-- Submenu content -->
            <div id='submenu2' class="collapse sidebar-submenu">
                <a href="{% url 'user:edit-profile' %}"
                   class="list-group-item list-group-item-action bg-dark text-white">
                    <span class="menu-collapsed">Personal</span>
                </a>

            </div>
            {% if user.is_staff %}
                <a href="{% url 'ticket:list-history-operator' %}"
                   class="bg-dark list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-start align-items-center">
                        <span class="fa fa-tasks fa-fw mr-3"></span>
                        <span class="menu-collapsed">History</span>
                    </div>
                </a> {% endif %}
            {% if user.is_superuser %}
                <!-- Separator with title -->
                <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed">
                    <small>OPTIONS</small>
                </li>
                <!-- /END Separator -->
                <a href="{% url 'ticket:list-history-replay' %}" class="bg-dark list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-start align-items-center">
                        <span class="fa fa-bar-chart fa-fw mr-3"></span>
                        <span class="menu-collapsed">Replay</span>
                    </div>
                </a>
                <a href="{% url 'ticket:list-history-query' %}" class="bg-dark list-group-item list-group-item-action">
                    <div class="d-flex w-100 justify-content-start align-items-center">
                        <span class="fa fa-bar-chart fa-fw mr-3"></span>
                        <span class="menu-collapsed">Query </span>
                        {#                                class="badge badge-pill badge-primary ml-2">5</span></span>#}
                    </div>
                </a>
            {% endif %}
            <!-- Separator without title -->
            <li class="list-group-item sidebar-separator menu-collapsed"></li>
            <!-- /END Separator -->
            <a href="#" class="bg-dark list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-question fa-fw mr-3"></span>
                    <span class="menu-collapsed">Help</span>
                </div>
            </a>
            {% if  user.is_authenticated %}
                <a href="{% url 'user:logout-user' %}" class="bg-dark list-group-item list-group-item-action"
                   class="bg-dark list-group-item list-group-item-action d-flex align-items-center">
                    <div class="d-flex w-100 justify-content-start align-items-center">
                        <span id="collapse-icon" class="fa fa-2x mr-3"></span>
                        <span id="collapse-text" class="menu-collapsed">Logout</span>
                    </div>
                </a>
            {% endif %}

        </ul><!-- List Group END-->
    </div><!-- sidebar-container END -->
{% endblock %}
<!-- MAIN -->
{% block content %}{% endblock %}

{% block base_content %}

{% endblock %}
</div><!-- body-row END -->
<script>
    // Hide submenus
    $('#body-row .collapse').collapse('hide');

    // Collapse/Expand icon
    $('#collapse-icon').addClass('fa-angle-double-left');

    // Collapse click
    $('[data-toggle=sidebar-colapse]').click(function () {
        SidebarCollapse();
    });

    function SidebarCollapse() {
        $('.menu-collapsed').toggleClass('d-none');
        $('.sidebar-submenu').toggleClass('d-none');
        $('.submenu-icon').toggleClass('d-none');
        $('#sidebar-container').toggleClass('sidebar-expanded sidebar-collapsed');

        // Treating d-flex/d-none on separators with title
        var SeparatorTitle = $('.sidebar-separator-title');
        if (SeparatorTitle.hasClass('d-flex')) {
            SeparatorTitle.removeClass('d-flex');
        } else {
            SeparatorTitle.addClass('d-flex');
        }

        // Collapse/Expand icon
        $('#collapse-icon').toggleClass('fa-angle-double-left fa-angle-double-right');
    }
</script>
{% block page_scripts %}{% endblock %}
</body>
</html>

helpdesk/dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block page_header_title %}
        Dashboard: {{ request.user.get_full_name }}
    {% endblock %}
</head>
{% block content %}
    <body>
    <div class="col p-4">
        <div class="card">
            <h5 class="card-header font-weight-light text-center">Dashboard: {{ request.user.get_full_name }}
                {% if messages %}
                    <div class="messages alert alert-primary" role="alert">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                {% endif %}
                </div>
            </h5>

            <div class="alert alert-dismissable alert-warning">
                <ul>
                    <li style="text-align: justify;"><strong>Ticketing Management</strong>: Help Desk Software enables
                        the user
                        to assign, prioritise and categorise tickets so that the user can keep track of them and
                        consequently
                        respond to them. The user can track, monitor and manage incoming customer support tickets from
                        different
                        channels in a single location. Help Desk Software enables the user to set ticket response and
                        problem
                        resolution deadlines depending on various categories and business hours. Help Desk Software
                        ensures that
                        multiple support agents don’t work on the same ticket accidentally and helps create custom
                        statuses that
                        suit the user workflow to identify what stage a particular ticket is in.
                    </li>
                    <li style="text-align: justify;"><strong>Collaboration</strong>: Enables the user to collaborate to
                        quickly
                        and efficiently address and resolve customer concerns. The user can link related tickets
                        together to
                        track common issues and deliver consistent responses. The user can discuss specific parts of
                        tickets
                        with experts from across the company to figure out how to address the customer concern and offer
                        the
                        right solutions. The user can share ticket ownership with other teams and view the progress
                        being made
                        on the issues.
                    </li>
                    <li style="text-align: justify;"><strong>Multichannel Support</strong>: The user can convert support
                        emails
                        into trackable tickets in the helpdesk so that they can manage and resolve them accordingly.
                        Help Desk
                        Software enables the user to set up a fully functional call centre that record and monitors call
                        by
                        converting them into tickets. The user can support, engage and retain customers through live
                        chat. Help
                        Desk Software can help integrate business social median handles to manage their concerns from
                        within the
                        helpdesk. Help Desk Software allows customers to raise tickets from the website and display
                        related
                        knowledge-base articles or answers to them as they type.
                    </li>
                    <li style="text-align: justify;"><strong>Automation</strong>: Automation feature enables the user to
                        perform
                        multiple actions on a ticket with a single click by automating repeated actions. The user can
                        offer
                        quick and consistent replies to common questions by creating pre-set responses. The user can
                        automatically assign tickets to agents and groups depending on various aspects as keywords,
                        enquirer or
                        properties. Help Desk Software enables the user to assign tickets to agents depending on their
                        current
                        workload and skills among other aspects. Help Desk Software updates customers and agents
                        automatically
                        about the progress of their ticket.
                    </li>
                    <li style="text-align: justify;"><strong>Self-Service portal</strong>: Allow the user to create a
                        self-service experience for customers and lets appropriate solutions to come up for customers
                        and agents
                        as they troubleshoot and try to resolve issues. Help Desk Software enables agents to convert
                        their
                        ticket responses into knowledge base articles as they reply to customers queries.
                    </li>
                    <li style="text-align: justify;"><strong>Reporting</strong>: The user can check how different agents
                        and
                        groups are performing depending on various helpdesk metrics. Help Desk Software allows the user
                        to gauge
                        customers’ satisfaction using customer satisfaction reports. The user can monitor the helpdesk
                        Dashboards using real-time data about tickets, groups and trends. Users access data and reports
                        to
                        gather custom insights to help in the business decision-making process. The user can get a
                        default and
                        custom reports in their inbox periodically.
                    </li>
                </ul>
            </div>

        </div>
    </div>
    </div>
    </body>
{% endblock %}
</html>