helpdesk/helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include

from ticket.views import QueryInfoAPI, ReplayInfoAPI

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('ticket/', include('ticket.urls')),
    path('', include('dashboard.urls')),
    path('api/', include('rest_framework.urls')),
    path('api/v1/query', QueryInfoAPI.as_view(), name='query-api'),
    path('api/v1/replay', ReplayInfoAPI.as_view(), name='replay-api'),
]

helpdesk/user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='create-user'),
    path('login/', views.LoginView.as_view(), name='login-user'),
    path('logout/', views.LogoutView.as_view(), name='logout-user'),
    path('edit/', views.EditProfile.as_view(), name='edit-profile'),
]

helpdesk/user/models.py
# from django.core.validators import RegexValidator
# from django.db import models
#
# # Create your models here.
# phone_re = RegexValidator(regex='^0[0-9]{2,}[0-9]{7,}$', message='شماره وارد شده صحیح نیست!')
#
# from django.contrib.auth.models import AbstractUser
#
# from simple_history import register
# from django.contrib.auth.models import User
#
# #
# #
# # class User(models.Model):
# #     """
# #     Register a user
# #     """
# #     name = models.CharField(max_length=30, blank=False, verbose_name='نام')
# #     last_name = models.CharField(max_length=30, blank=False, verbose_name='نام خانوادگی')
# #     email = models.EmailField(max_length=50, blank=False, verbose_name='ایمیل')
# #     phone = models.CharField(max_length=11, unique=True, validators=[phone_re], verbose_name='شماره موبایل')
# #     last_login = models.DateTimeField(auto_now=True, verbose_name='اخرین ورود')
# #
# #     def __str__(self):
# #         """
# #         :return: define name
# #         """
# #         return self.name, self.last_name

helpdesk/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name']

helpdesk/user/views.py
# Create your views here.
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView

from .forms import UserRegisterForm


class SignUpView(SuccessMessageMixin, CreateView):
    """
    Register user to website financial
    """
    template_name = 'user/create-signup.html'
    success_url = reverse_lazy('dashboard:dashboard')
    form_class = UserRegisterForm
    success_message = "%(username)s Your profile was created successfully"


class LogoutView(SuccessMessageMixin, LogoutView):
    template_name = 'user/LogoutView_form.html'
    success_url = reverse_lazy('user:login-user')
    success_message = "Good Bye %(username)s "


class LoginView(SuccessMessageMixin, LoginView):
    template_name = 'user/LoginView_form.html'
    success_url = reverse_lazy('dashboard:dashboard')
    success_message = "Welcome %(username)s "


class EditProfile(LoginRequiredMixin, UpdateView):
    """
    Updates a user profile
    """
    model = get_user_model()
    fields = (
        'first_name',
        'last_name',
        'email',
    )
    template_name = 'user/edit-profile.html'
    success_url = reverse_lazy('dashboard:dashboard')
    success_message = " %(username)s your profile changed successfully"

    def get_object(self, queryset=None):
        return self.request.user

helpdesk/user/templates/user/LoginView_form.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}
<html>
<head>
    {% block page_header_title %} Login {% endblock %}
</head>
<body>

{% block base_content %} {% endblock %}
{% block content %}

    <div style="margin-top: 1%" class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card-group mb-0">
                    <div class="card p-4">
                        <form method="post">{% csrf_token %}
                            <div class="card-body">
                                <h1>Login</h1>
                                <p class="text-muted">Sign In to your account</p>
                                <div class="input-group mb-3">
                                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                    {% render_field form.username class="form-control" placeholder=form.username.label %}
                                </div>
                                <div class="input-group mb-4">
                                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                    {% render_field form.password class="form-control" placeholder=form.password.label %}
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <button type="submit" class="btn btn-primary px-4">Login</button>
                                    </div>
                                    <div class="col-6 text-right">
                                        <a href="{% url 'user:create-user' %}" class="btn btn-link px-0">Forgot
                                            password?
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="cart text-white bg-primary py-5 d-md-down-none" style="width:44%">
                        <div class="card-body text-center">
                            <div>
                                <h2>Sign up</h2>
                                <p>ticketing system | help desk
                                    <br>Is a resource intended to provide the customer or end user with
                                    information and support related to a company's or institution's products and
                                    services.</p>
                                <a href="{% url 'user:create-user' %}" class="btn btn-primary active mt-3">Register
                                    Now!</a>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>

</html>
<style>
    body {
        margin-top: 20px;
        background: #4c535d;
    }

    .cart-vody {
        background-color: #3fc0ad;
    }

    .container {
        margin-right: auto;
        margin-left: auto;
        padding-right: 15px;
        padding-left: 15px;
        width: 100%;
    }

    @media (min-width: 576px) {
        .container {
            max-width: 540px;
        }
    }

    @media (min-width: 768px) {
        .container {
            max-width: 720px;
        }
    }

    @media (min-width: 992px) {
        .container {
            max-width: 960px;
        }
    }

    @media (min-width: 1200px) {
        .container {
            max-width: 1140px;
        }
    }


    .card-columns .card {
        margin-bottom: 0.75rem;
    }

    @media (min-width: 576px) {
        .card-columns {
            column-count: 3;
            column-gap: 1.25rem;
        }

        .card-columns .card {
            display: inline-block;
            width: 100%;
        }
    }

    .text-muted {
        color: #9faecb !important;
    }

    p {
        margin-top: 0;
        margin-bottom: 1rem;
    }

    .mb-3 {
        margin-bottom: 1rem !important;
    }

    .input-group {
        position: relative;
        display: flex;
        width: 100%;
    }
</style>

helpdesk/user/templates/user/create-signup.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
    {% block page_header_title %}Sign up{% endblock %}
</head>
<body>
{% block content %}
    <div class="signup-form">
        <form method="post">
            <h2>Sign Up</h2>
            <p>Ticketing system | Help desk.</p>
            <hr>
            {% csrf_token %}
            <div class="form-group">
                {% render_field form.username class="form-control" placeholder=form.username.label %}
            </div>
            <div class="form-group">
                {% render_field form.email class="form-control" placeholder=form.email.label %}
            </div>
            <div class="form-group">
                {% render_field form.password1 class="form-control" placeholder=form.password1.label %}
            </div>
            <div class="form-group">
                {% render_field form.password2 class="form-control" placeholder=form.password2.label %}
            </div>

            <button type="submit" name="submit" class="btn btn-primary btn-block btn-lg">Sign Up</button>
        </form>
        <div class="form-group">
        </div>
        <p class="small text-center">By clicking the Sign Up button, you agree to our <br><a href="#">Terms &amp;
            Conditions</a>, and <a href="#">Privacy Policy</a>.</p>
        <div class="text-center">Already have an account? <a href="{% url 'user:login-user' %} ">Login here</a></div>
    </div>

{% endblock %}
</body>
</html>

{% block head %}
    <style>
        body {
            color: #fff;
            background: #4c535d;
            font-family: 'Roboto', sans-serif;
        }

        .form-control {
            min-height: 41px;
            box-shadow: none;
            border-color: #e1e4e5;
            font-size: 14px;
        }

        .form-control, .btn {
            border-radius: 3px;
        }

        .signup-form {
            width: 400px;
            margin: 0 auto;
            padding: 30px 0;
        }

        .signup-form form {
            color: #9ba5a8;
            border-radius: 3px;
            margin-bottom: 15px;
            background: #fff;
            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
            padding: 30px;
        }

        .signup-form h2 {
            color: #333;
            font-weight: bold;
            margin-top: 0;
        }

        .signup-form hr {
            margin: 0 -30px 20px;
        }

        .signup-form .form-group {
            margin-bottom: 20px;
        }

        .signup-form label {
            font-weight: normal;
            font-size: 13px;
        }

        .signup-form .btn, .signup-form .btn:active {
            font-size: 16px;
            font-weight: bold;
            background: #337ab7 !important;
            border: none;
            min-width: 140px;
        }

        .signup-form .btn:hover, .signup-form .btn:focus {
            background: #3fc0ad !important;
        }

        .signup-form a {
            color: #fff;
            text-decoration: underline;
        }

        .signup-form a:hover {
            text-decoration: none;
        }

        .signup-form form a {
            color: #5fcaba;
            text-decoration: none;
        }

        .signup-form form a:hover {
            text-decoration: underline;
        }
    </style>
{% endblock %}

helpdesk/user/templates/user/edit-profile.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}

    {% block page_header_title %}
        Profile: {{ request.user.get_full_name }}
    {% endblock %}

{% block base_content %}
    <div class="col p-4">
        <div class="card">
            <h5 class="card-header font-weight-light text-center">Profile: {{ request.user.get_full_name }}
                {% if messages %}
                    <div class="messages alert alert-primary" role="alert">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                {% endif %}v
                </div>
            </h5>
            <form method="post">
                {% csrf_token %}
                <label for="title">نام:</label>
                {{ form.first_name | add_class:'form-control' }}
                <label for="title">نام خانوادگی: </label>
                {{ form.last_name  | add_class:'form-control' }}
                <label for="title">ایمیل:</label>
                {{ form.email | add_class:'form-control' }}
                <input type="submit" name="summit">
            </form>
        </div>
    </div>
{% endblock %}