helpdesk/helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include

from ticket.views import QueryInfoAPI, ReplayInfoAPI

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('ticket/', include('ticket.urls')),
    path('', include('dashboard.urls')),
    path('api/', include('rest_framework.urls')),
    path('api/v1/query', QueryInfoAPI.as_view(), name='query-api'),
    path('api/v1/replay', ReplayInfoAPI.as_view(), name='replay-api'),
]

helpdesk/ticket/urls.py
from django.urls import path

from . import views

app_name = 'ticket'
urlpatterns = [
    path('create/', views.CreateQuery.as_view(), name='create-ticket'),
    path('view/', views.show_active_query, name='view-ticket'),
    path('detail/<str:pk>', views.DetailQueryReplay.as_view(), name='detail-query'),
    path('edit/<str:pk>', views.EditQueryCategoryView.as_view(), name='edit-query'),
    path('history/replay', views.HistoryListViewReplay.as_view(), name='list-history-replay'),
    path('history/operator', views.HistoryListViewOperator.as_view(), name='list-history-operator'),
    path('history/query', views.HistoryListViewQuery.as_view(), name='list-history-query'),
    path('close/<int:id>', views.set_cancel_status_query, name='close-query'),
]

helpdesk/user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='create-user'),
    path('login/', views.LoginView.as_view(), name='login-user'),
    path('logout/', views.LogoutView.as_view(), name='logout-user'),
    path('edit/', views.EditProfile.as_view(), name='edit-profile'),
]

helpdesk/ticket/models.py
from django.db import models
# Create your models here.
from django.utils.text import slugify
# from simple_history.models import HistoricalRecords
from simple_history.models import HistoricalRecords

from ticket import enums


class Query(models.Model):
    """
    Create query ticket
    """
    subject = models.CharField(max_length=30, blank=False, verbose_name='موضوع تیکت')
    message = models.CharField(max_length=500, blank=False, verbose_name='متن تیکت')
    status = models.CharField(max_length=20, choices=enums.TicketStatuses.choices,
                              default=enums.TicketStatuses.CREATED, verbose_name='وضعیت تیکت')
    is_active = models.BooleanField(default=True, verbose_name='فعال است؟')
    create_info = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    slug = models.SlugField(max_length=50, unique=True, editable=False)
    # ForeignKey
    user_related = models.ForeignKey('auth.User', on_delete=models.PROTECT, verbose_name='رابطه با کاربران', null=True,
                                     blank=True)
    category_related = models.ForeignKey('ticket.Category', on_delete=models.PROTECT, verbose_name='رابطه با کتگوری',
                                         null=True,
                                         blank=True)
    operator_related = models.CharField(max_length=20, default=0, verbose_name='ادمین این تیکت')
    history = HistoricalRecords()

    def __str__(self):
        """
        :return: define name
        """
        return self.subject

    def save(self, *args, **kwargs):
        """
        auto add slug
        """
        if not self.id:
            self.slug = slugify(self.subject, allow_unicode=True)
        super().save(*args, **kwargs)

    def close_query(self):
        if self.is_active:
            self.is_active = False
            self.status=enums.TicketStatuses.CANCELED
            return True
        else:
            return False


class Replay(models.Model):
    """
    Create replay ticket
    """
    replay_message = models.CharField(max_length=500, blank=False, verbose_name='پاسخ تیکت')
    create_info = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    query_related = models.ForeignKey('ticket.Query', on_delete=models.CASCADE, verbose_name='کلید جواب برای سوال',
                                      null=True,
                                      blank=True)
    operator_related = models.ForeignKey('auth.User', on_delete=models.PROTECT, verbose_name='کلید شخص برای سوال',
                                         null=True,
                                         blank=True)
    history = HistoricalRecords()

    def __str__(self):
        """
        :return: define name
        """
        return self.replay_message


class Category(models.Model):
    """
    Create category for tickets and operators
    """
    category_name = models.CharField(max_length=100, blank=False, unique=True, verbose_name='دسته بندی تیکت')
    slug = models.SlugField(max_length=50, unique=True, editable=False)
    history = HistoricalRecords()

    # query_related = models.ForeignKey('ticket.Query', on_delete=models.PROTECT, verbose_name='رابطه با پرسش')

    def __str__(self):
        """
        :return: define name
        """
        return self.category_name

    def save(self, *args, **kwargs):
        """
        auto add slug
        """
        if not self.id:
            self.slug = slugify(self.category_name, allow_unicode=True)
        super().save(*args, **kwargs)

helpdesk/ticket/forms.py
from django import forms

from ticket import models


class CreateQueryForm(forms.ModelForm):
    class Meta:
        model = models.Query
        fields = (
            'subject',
            'message',
            'category_related',
        )


class EditQueryCategoryForm(forms.ModelForm):
    class Meta:
        model = models.Query
        fields = (
            'status',
            'user_related',
            'category_related',
            'is_active',
        )
        widgets = {
            'is_active': forms.CheckboxInput,
        }

    widgets = {
        'status': forms.Select,
        'user_related': forms.Select,
        'query_related': forms.Select,
    }


class CreateReplayForm(forms.ModelForm):
    """
    create replay with (operator_related and query_related) AJAX
    """

    class Meta:
        model = models.Replay
        fields = ('replay_message',
                  )

    widgets = {
        'replay_message': forms.TextInput,

    }

helpdesk/ticket/views.py
import itertools

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from django.views.generic.edit import FormMixin
from rest_framework.exceptions import NotAuthenticated
from rest_framework.generics import ListAPIView

from ticket import models, serializers
from ticket.forms import CreateQueryForm, EditQueryCategoryForm, CreateReplayForm


class CreateQuery(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
        Create a query ticket
    """
    model = models.Query
    form_class = CreateQueryForm
    template_name = 'ticket/create_ticket.html'
    success_message = "Your message has been successfully registered"
    success_url = reverse_lazy('ticket:view-ticket')

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.operator_related = self.request.user
        obj.save()
        return super(CreateQuery, self).form_valid(form)


class EditQueryCategoryView(LoginRequiredMixin, UpdateView):
    """
        Redirect query category by operators
    """
    model = models.Query
    template_name = 'ticket/edit-query.html'
    form_class = EditQueryCategoryForm
    success_message = "Reference has been successfully"
    success_url = reverse_lazy('ticket:view-ticket')


class DetailQueryReplay(LoginRequiredMixin, FormMixin, DetailView):
    """
         Show a list of Replays for every single query
     """

    model = models.Query
    template_name = 'ticket/detail-query.html'
    form_class = CreateReplayForm
    success_message = "done successfully"
    success_url = reverse_lazy('ticket:view-ticket')


    def get_context_data(self, **kwargs):
        context = super(DetailQueryReplay, self).get_context_data(**kwargs)
        context['form'] = CreateReplayForm(initial={'post': self.object})
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):

        obj = form.save(commit=False)
        obj.operator_related = self.request.user
        obj.query_related = self.object
        models.Query.objects.filter(pk=self.kwargs.get('pk')).update(operator_related=self.request.user.pk)
        models.Query.objects.filter(pk=self.kwargs.get('pk')).update(status='RESOLVED')
        obj.save()
        return super(DetailQueryReplay, self).form_valid(obj)

    def form_invalid(self, form):
        JsonResponse({'message': 'form is not valid '})


class CreateReplay(LoginRequiredMixin, CreateView):
    """
    AJAX: Create Replay to one Query
    """
    template_name = 'ticket/detail-query.html'
    form_class = CreateReplayForm
    success_message = "%(operator_related)s Your Query create successfully"
    success_url = reverse_lazy('dashboard:dashboard')


@login_required
def show_active_query(request):
    """
        Show all query that resolved or not
        filter by operators and users
    """
    qs_list1, qs_list2 = 0, 0

    if request.user.is_authenticated:
        if request.user.is_superuser:
            try:
                # list1: query is resolve (up)
                qs_list1 = models.Query.objects.filter(~Q(operator_related__exact='0'))
                # list2: query not resolved (down)
                qs_list2 = models.Query.objects.filter(operator_related__exact='0')
            except:
                return render(request, 'dashboard/dashboard.html')
        elif request.user.is_staff:
            try:
                qs_list1 = models.Query.objects.filter(
                    Q(operator_related=request.user.pk) & Q(is_active=1)
                )
                qs_list2 = models.Query.objects.filter(
                    Q(operator_related__exact='0') & Q(category_related=request.user.category)
                )
            except:
                return render(request, 'dashboard/dashboard.html')
        else:
            try:
                qs_list1 = models.Query.objects.filter(
                    Q(user_related=request.user) & Q(is_active=1)
                )
                qs_list2 = models.Query.objects.filter(
                    Q(user_related=request.user) & Q(is_active=0)
                )
            except:

                return render(request, 'dashboard/dashboard.html')
    else:
        return render(request, 'dashboard/dashboard.html')
    # --------------------paginator--------------------
    other_number = []
    qs = list(itertools.chain(qs_list1, other_number))
    paginated = Paginator(qs, 4)
    paginated_page = paginated.get_page(request.GET.get('page', 1))
    return render(request=request,
                  context={'object_list': paginated_page,
                           'qs_list2': qs_list2
                           },
                  template_name='ticket/list-query.html')


class HistoryListViewReplay(LoginRequiredMixin, ListView):
    """
    show a list of replay histories and references (for admin)
    """
    model = models.Replay
    template_name = 'ticket/list-history-replay.html'
    extra_context = {'ReplayHistories': models.Replay.history,
                     }
    paginate_by = 5

    def get_queryset(self):
        qs = super().get_queryset().order_by('id')
        if self.request.user.is_authenticated:
            try:
                if self.request.user.is_superuser:
                    return qs
            # return qs.filter(user_related=self.request.user)
            except:
                return qs.EmptyQuerySet


class HistoryListViewQuery(LoginRequiredMixin, ListView):
    """
    show a list of query histories (for admin)
    """
    model = models.Query
    template_name = 'ticket/list-history-query.html'
    extra_context = {'ReplayHistories': models.Query.history,
                     }
    paginate_by = 5

    def get_queryset(self):
        qs = super().get_queryset().order_by('id')
        if self.request.user.is_authenticated:
            try:
                if self.request.user.is_superuser:
                    return qs
            # return qs.filter(user_related=self.request.user)
            except:
                return qs.EmptyQuerySet


class HistoryListViewOperator(LoginRequiredMixin, ListView):
    """
    show a list of replay history that filter by operator (for operator)
    """
    model = models.Replay
    template_name = 'ticket/list-history-operator.html'
    extra_context = {'ReplayHistories': models.Replay.history,
                     }
    paginate_by = 5

    def get_queryset(self):
        qs = super().get_queryset().order_by('id')
        if self.request.user.is_authenticated:
            try:
                if self.request.user.is_staff:
                    qs = models.Replay.objects.filter(operator_related=self.request.user)
                    return qs
                    # return qs.filter(user_related=self.request.user)
            except:
                return qs.EmptyQuerySet


def set_cancel_status_query(request, id):
    """
    :param id: it's the object id
    :return:  set False for is_active field else return expire time
    """
    product_instance = get_object_or_404(models.Query, pk=id)
    if product_instance.close_query():
        product_instance.save()
        messages.success(request, "The ticket was closed")
        return redirect('ticket:view-ticket')
    else:
        messages.error(request, 'the query time is expired')
        return redirect('ticket:view-ticket')


# --------------------------------------------REST-API-----------------------------------------------------

class QueryInfoAPI(ListAPIView):
    """
    API  all Query related with operator
    """

    serializer_class = serializers.QuerySerializer
    queryset = models.Query.objects.all()

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_superuser:
            return qs
        if self.request.user.is_anonymous:
            raise NotAuthenticated('You need to be logged on.')
        return qs.filter(user_related=self.request.user)


class ReplayInfoAPI(ListAPIView):
    """
    API  all Replay related with operator
    """
    serializer_class = serializers.ReplaySerializer
    queryset = models.Replay.objects.all()

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_superuser:
            return qs
        if self.request.user.is_anonymous:
            raise NotAuthenticated('You need to be logged on.')
        return qs.filter(operator_related=self.request.user)

helpdesk/ticket/templates/ticket/create_ticket.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}
{% block page_header_title %}
    Edit: {{ query.create_info }}
{% endblock %}
{% block content %}
    <div class="col p-4">
        <div class="card">
            <h5 class="card-header font-weight-light text-center">Dashboard: {{ request.user.get_full_name }}
                {% if messages %}
                    <div class="messages alert alert-primary" role="alert">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                {% endif %}
                </div>
            </h5>

            <div class="col-2 center-">
                <form method="post">
                    {% csrf_token %}
                    {{ form.email }}
                    {{ form.username }}
                    <label for="title">Subject:</label>
                    {{ form.subject | add_class:'form-control' }}
                    <label for="title">Text: </label>
                    {{ form.message  | add_class:'form-control' }}
                    <label for="title">Issue:</label>
                    {{ form.category_related | add_class:'form-control' }}
                    <input type="submit" name="summit">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

helpdesk/ticket/templates/ticket/detail-query.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}
{% block page_header_title %}
    Query: {{ query.subject }}
{% endblock %}
{% block base_content %}
    <div class="container">
        <div class="row">
            <div class="col p-2">
                <h5 class="card-header font-weight-light text-left">The query subject : {{ query.subject }}

                    {% if messages %}
                        <div class="messages alert alert-primary" role="alert">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    {% endif %}
                    </div>
                </h5>
            </div>
            <div class="row">
                <div class="col p-2">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Category: {{ query.category_related }}</th>
                            <th class="text-right" scope="col">Date: {{ query.create_info }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if user.pk == query.user_related.pk %}
                        {% else %}
                        {% endif %}
                        <td class="text-left alert-info">{{ query.create_info.time }}</td>
                        <td class="text-right alert-info">{{ query.message }}</td>
                        <tr>
                            {% for item in object.replay_set.all %}
                                {% if user.pk == item.operator_related.pk %}
                                    <td class="text-left alert-info">{{ item.create_info.time }}</td>
                                    <td class="text-right alert-info">{{ item.replay_message }}</td>
                                {% else %}
                                    <td class="text-left alert-dark">{{ item.replay_message }}</td>
                                    <td class="text-right alert-dark">{{ item.create_info.time }}</td>
                                {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <form method="post">
                        {% csrf_token %}<br>
                        {{ form.replay_message|add_class:'form-control form-text' }}<br>
                        <button id="send-form" class="d-inline p-2 bg-primary text-white mr-5 btn btn-primary "
                                name="submit">save
                        </button>
                        {% if user.is_staff %}
                            <a href="{% url 'ticket:edit-query' object.pk %}" id="" class="d-inline p-2 bg-primary text-white btn btn-primary ml-5 bg-warning
                                 ">reference</a>
                            <a href="{% url 'ticket:edit-query' object.pk %}" id=""
                               class="d-inline p-2 bg-primary text-white btn btn-primary bg-info ">print</a>

                            <a href="{% url 'ticket:edit-query' object.pk %}" id=""
                               class="d-inline p-2 bg-primary text-white btn btn-primary   bg-info">email</a>
                            <a href="{% url 'ticket:close-query' object.pk %}" id=""
                               class="d-inline p-2 bg-primary text-dark btn btn-primary bg-danger ">close</a>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

helpdesk/ticket/templates/ticket/edit-query.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}
{% block page_header_title %}
    Edit: {{ query.create_info }}
{% endblock %}
{% block content %}
    <div class="col p-4">
        <div class="card">
            <h5 class="card-header font-weight-light text-center">Dashboard: {{ request.user.get_full_name }}
                {% if messages %}
                    <div class="messages alert alert-primary" role="alert">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                {% endif %}
                </div>
            </h5>
            <div class="col-2 center-">
                <form method="post">
                    {% csrf_token %}
                    <label for="title">Status:</label>
                    {{ form.status | add_class:'form-control' }}
                    <label for="title">Operators: </label>
                    {{ form.user_related  | add_class:'form-control' }}
                    <label for="title">Issue:</label>
                    {{ form.category_related | add_class:'form-control' }}<br>
                    <label for="title">Active:</label>
                    {{ form.is_active | add_class:'form-check-inline' }}<br><br>
                    <input type="submit" name="summit">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

helpdesk/ticket/templates/ticket/list-history-operator.html
{% extends 'dashboard/base.html' %}

    <meta charset="UTF-8">
    {% block page_header_title %}
        History
    {% endblock %}

{% block base_content %}
    {#    --------------------------------------Replay histories-------------------------------#}
    <body>
    <div class="col p-4">
        <div class="card">
            <h5 class="card-header font-weight-light text-center">All replay histories: {{ request.user.get_full_name }}
                {% if messages %}
                    <div class="messages alert alert-primary" role="alert">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                {% endif %}
                </div>
            </h5>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Row</th>
                    <th scope="col">replay_message</th>
                    <th scope="col">create_info</th>
                    <th scope="col">query_related</th>
                    <th scope="col">operator_related</th>
                </tr>
                </thead>

                {% for org in ReplayHistories.all %}
                    <tbody>
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ org.replay_message }}</td>
                        <td>{{ org.create_info }}</td>
                        <td>{{ org.query_related }}</td>
                        <td>{{ org.operator_related }}</td>
                        <td>{{ org.is_active }}</td>
                    </tr>
                    </tbody>
                {% endfor %}
            </table>
            {% include 'ticket/pagination.html' %}
        </div>
    </div>


   </body>
{% endblock %}

helpdesk/ticket/templates/ticket/list-history-query.html
{% extends 'dashboard/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block page_header_title %}
        History
    {% endblock %}
</head>

{% block base_content %}
    {#    --------------------------------------Replay histories-------------------------------#}
    <body>
    <div class="col p-4">
        <div class="card">
            <h5 class="card-header font-weight-light text-center">All Query & Reference
                histories {{ request.user.get_full_name }}
                {% if messages %}
                    <div class="messages alert alert-primary" role="alert">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                {% endif %}
                </div>
            </h5>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Row</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Referenced</th>
                    <th scope="col">Text</th>
                    <th scope="col">Status</th>
                    <th scope="col">Active</th>
                    <th scope="col">Date</th>
                </tr>
                </thead>

                {% for org in ReplayHistories.all %}
                    <tbody>
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ org.subject }}</td>
                        <td>
                            {% if  org.history_type == '~' %}
                                Referenced
                            {% else %}
                                Create
                            {% endif %}
                        </td>
                        <td>{{ org.message }}</td>
                        <td>{{ org.status }}</td>
                        <td>{{ org.is_active }}</td>
                        <td>{{ org.history_date }}</td>
                        </a></td>
                    </tr>
                    </tr>
                    </tbody>
                {% endfor %}
            </table>
            {% include 'ticket/pagination.html' %}
        </div>
    </div>

{% endblock %}
</body>
</html>

helpdesk/ticket/templates/ticket/list-query.html
{% extends 'dashboard/base.html' %}
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
{% block page_header_title %}
    Quote lis: dwq
{% endblock %}

{% block base_content %}
    <div class="container">
        <div class="row">
            <div class="col p-2">
                <h5 class="card-header font-weight-light text-left">
                {% if   request.user.is_superuser %}
                    All query that resolved:
                {% elif request.user.is_staff %}
                      Query resolved by: {{ request.user.get_full_name }}
                {% else %}
                    Your active queries:  {{ request.user.get_full_name }}
                {% endif %}
                     {% if messages %}
                        <div class="messages alert alert-primary" role="alert">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    {% endif %}
                    </div>
                </h5>
            </div>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Row</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Text</th>
                    <th scope="col">Status</th>
                    <th scope="col">Is_active</th>
                    <th scope="col">Date</th>
                    <th scope="col">History</th>
                    <th scope="col">Reference</th>
                    <th scope="col">Print</th>
                </tr>
                </thead>
                {% for org in object_list %}
                    <tbody>
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ org.subject }}</td>
                        <td>{{ org.message }}</td>
                        <td>{{ org.status }}</td>
                        <td>{{ org.is_active }}</td>
                        <td>{{ org.create_info }}</td>
                        <td><a href="{% url 'ticket:detail-query' org.pk %}">Chat</a></td>
                        <td><a href="{% url 'ticket:edit-query' org.pk %}">Edit</a></td>
                        <td><a href="{% url 'ticket:detail-query' org.pk %}">Export</a></td>
                    </tr>
                    </tbody>
                {% endfor %}
            </table>
            {% include 'ticket/pagination.html' %}
            <h5 class="card-header font-weight-light text-left">
                    {% if   request.user.is_superuser %}
                    All query in queue:
                {% elif request.user.is_staff %}
                      Query resolved by: {{ request.user.get_full_name }}
                {% else %}
                    Your expired queries:  {{ request.user.get_full_name }}
                {% endif %}
            </h5>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Row</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Text</th>
                    <th scope="col">Status</th>
                    <th scope="col">Is_active</th>
                    <th scope="col">Date</th>
                    <th scope="col">History</th>
                    <th scope="col">Reference</th>
                    <th scope="col">Print</th>
                </tr>
                </thead>
                {% for org in qs_list2 %}
                    <tbody>
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ org.subject }}</td>
                        <td>{{ org.message }}</td>
                        <td>{{ org.status }}</td>
                        <td>{{ org.is_active }}</td>
                        <td>{{ org.create_info }}</td>
                        <td><a href="{% url 'ticket:detail-query' org.pk %}">Chat</a></td>
                        <td><a href="{% url 'ticket:edit-query' org.pk %}">Edit</a></td>
                        <td><a href="{% url 'ticket:detail-query' org.pk %}">Export</a></td>
                    </tr>
                    </tbody>
                {% endfor %}
            </table>
            {% include 'ticket/pagination.html' %}


        </div>
    </div>




{% endblock %}

</html>

helpdesk/ticket/templates/ticket/pagination.html
{% if object_list.has_previous %}
    <a class="btn btn-sm" href="{{ request.path }}?page={{ object_list.previous_page_number }}">back</a>
{% else %}
    <a class="btn btn-sm" href="{{ request.path }}?page=1">First Page</a>
{% endif %}

{% for n in page_obj %}
    <a class="btn btn-sm" href="{{ request.path }}?page={{ n.number }}">{{ n.number }}</a>
{% endfor %}

{% if object_list.has_next %}
    <a class="btn btn-sm" href="{{ request.path }}?page={{ object_list.next_page_number }}">next</a>
{% else %}
    <a class="btn btm-sm" href="{{ request.path }}?page={{ page_obj.num_pages }}">Last page</a>
{% endif %}